version: '3'
services:
  db:
    image: mongo:jessie
    environment:
      MONGO_INITDB_DATABASE: "labcodeKBB"
      MONGO_DATA_DIR: "/data/db"
    volumes:
      - ./db:/data/db
    ports:
      - "0.0.0.0:40023:27017"
  backend:
    build: ./backend
    volumes:
    # only for development
      - ./backend/:/app
    ports:
      - "0.0.0.0:40022:4000"
    links:
      - db
    depends_on:
      - db
  frontend:
    image: node:10
    volumes:
      - ./frontend:/app
    ports:
      - "0.0.0.0:40021:4200"
    command: bash -c "cd /app && npm install && node node_modules/.bin/ng serve --host 0.0.0.0"
    depends_on:
      - backend
