version: '3'
services:
  db:
    image: mongo:jessie
    environment:
      MONGO_INITDB_DATABASE: "labcodeKBB"
      MONGO_DATA_DIR: "/data/db"
    volumes:
      - ./db:/data/db
    ports:
      - "0.0.0.0:40012:27017"
  backend:
    build: ./backend
    volumes:
    # only for development
      - ./backend/:/app
    ports:
      - "0.0.0.0:40011:4000"
    links:
      - db
    depends_on:
      - db
#  frontend:
#    image: nginx
#    volumes:
#      - ./frontend:/usr/share/nginx/html
#    ports:
#      - "0.0.0.0:40012:80"
#    depends_on:
#      - backend