swagger: "2.0"
info:
  version: "1.0.0"
  title: "FEINT"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
# host: "feint-server.labcode.de"
schemes:
  - "https"
paths:
  /user/getProfile:
    get:
      tags:
        - "user"
      summary: "Get the current authenticated User"
      description: ""
      operationId: "getUserProfile"
      produces:
        - "application/json"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/User"
        401:
          description: "Unauthorized"
      security:
        - token: []
  /control/changeProfile:
    post:
      tags:
        - "control"
      summary: "Change the current authenticated User"
      description: ""
      parameters:
        - in: body
          required: true
          name: body
          description: ""
          schema:
            $ref: '#/definitions/UserChange'
      operationId: "changeUserProfile"
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
        400:
          description: "Bad Request"
        401:
          description: "Unauthorized"
        500:
          description: "DB Error"
      security:
        - token: []
  /event/createEvent:
    post:
      tags:
        - "event"
      summary: "add event"
      description: ""
      parameters:
        - in: body
          required: true
          name: body
          description: ""
          schema:
            $ref: "#/definitions/CreateEvent"
      operationId: 'createEvent'
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
        400:
          description: "Identifier used"
        401:
          description: "Unauthorized"
      security:
        - token: []
  /event/addTokenEvent:
    post:
      tags:
        - "event"
      summary: "add event"
      description: ""
      parameters:
        - in: body
          required: true
          name: body
          description: ""
          schema:
            $ref: "#/definitions/AddTokenEvent"
      operationId: 'Event'
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
        400:
          description: "Token incorrect"
        401:
          description: "Unauthorized"
      security:
        - token: []
  /event/{eventId}/getFamilyStats:
    get:
      tags:
        - "event"
      summary: "get family stats of event"
      description: ""
      parameters:
        - in: "path"
          name: "eventId"
          type: string
          required: true
          description: eventIdentifier of the event to get
      operationId: 'getEventFamilyStats'
      produces:
        - "application/json"
      responses:
        200:
          description: "OK"
          schema:
            $ref: "#/definitions/FamilyStats"
      security:
        - token: []
securityDefinitions:
  token:
    type: "apiKey"
    name: "x-access-token"
    in: "header"
definitions:
  CreateEvent:
    type: 'object'
    properties:
      name:
        type: "string"
      identifier:
        type: "string"
  AddTokenEvent:
    type: 'object'
    properties:
      token:
        type: "string"
  UserChange:
    type: "object"
    properties:
      firstName:
        type: "string"
      familyName:
        type: "string"
  User:
    type: "object"
    properties:
      _id:
        type: "string"
        description: "MongoDB ID"
      authenticatedServices:
        type: 'string'
      googleID:
        type: "string"
      email:
        type: "string"
      amount:
        type: "number"
      name:
        type: "object"
        properties:
          familyName:
            type: "string"
          givenName:
            type: "string"
      allowedEvents:
        type: "array"
        items:
          type: "object"
          description: "Events"
          properties:
            eventId:
              type: "string"
            name:
              type: "string"
            identifier:
              type: "string"
  FamilyStats:
    type: "object"
    properties:
      families:
        type: "array"
        items:
          type: "object"
          properties:
            name:
              type: "string"
              description: "FamilyName"
            numPeople:
              type: "number"
            numDays:
              type: "number"
            peopleDays:
              type: "number"
            share:
              type: "number"
              description: "Anteil am Geld"
            currentAmount:
              type: "number"
              description: "Current Amount of family"
            debit:
              type: "number"
              description: "Soll"
      totalAmount:
        type: "number"
      totalDebit:
        type: "number"
      totalPeopleDays:
        type: "number"
      name:
        type: "string"